apiVersion: v1
kind: Service
metadata:
  name: otter-identity
spec:
  type: LoadBalancer
  selector:
    app: otter-identity
  ports:
    - name: grpc
      port: 50050
      targetPort: 50050
      protocol: TCP
